/*****************************  Auth Constants  *************************************/

export const SIGNIN = "SIGNIN";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const IS_LOGGED_IN_SUCCESS = "IS_LOGGED_IN_SUCCESS";
export const IS_LOGGED_IN_FAILURE = "IS_LOGGED_IN_FAILURE";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const SWITCH_USER_MOOD = "SWITCH_USER_MOOD";

/*****************************  Venues Constants  *************************************/

export const GET_VENUES = "GET_VENUES";
export const GET_VENUES_SUCCESS = "GET_VENUES_SUCCESS";
export const GET_VENUES_FAILURE = "GET_VENUES_FAILURE";

export const GET_VENUE = "GET_VENUE";
export const GET_VENUE_SUCCESS = "GET_VENUE_SUCCESS";
export const GET_VENUE_FAILURE = "GET_VENUE_FAILURE";

export const SAVE_VENUES = "SAVE_VENUES";
export const SAVE_VENUES_SUCCESS = "SAVE_VENUES_SUCCESS";
export const SAVE_VENUES_FAILURE = "SAVE_VENUES_FAILURE";

export const SAVE_CUSTOM_BOOKING = "SAVE_CUSTOM_BOOKING";
export const SAVE_CUSTOM_BOOKING_SUCCESS = "SAVE_CUSTOM_BOOKING_SUCCESS";
export const SAVE_CUSTOM_BOOKING_FAILURE = "SAVE_CUSTOM_BOOKING_FAILURE";

export const UPDATE_VENUE = "UPDATE_VENUES";
export const UPDATE_VENUE_SUCCESS = "UPDATE_VENUES_SUCCESS";
export const UPDATE_VENUE_FAILURE = "UPDATE_VENUES_FAILURE";

export const GET_ARCHIVE_VENUES = "GET_ARCHIVE_VENUES";
export const GET_ARCHIVE_VENUES_SUCCESS = "GET_ARCHIVE_VENUES_SUCCESS";
export const GET_ARCHIVE_VENUES_FAILURE = "GET_ARCHIVE_VENUES_FAILURE";

export const CREATE_PACKAGES = "CREATE_PACKAGES";
export const CREATE_PACKAGES_SUCCESS = "CREATE_PACKAGES_SUCCESS";
export const CREATE_PACKAGES_FAILURE = "CREATE_PACKAGES_FAILURE";

export const GET_PACKAGES = "GET_PACKAGES";
export const GET_PACKAGES_SUCCESS = "GET_PACKAGES_SUCCESS";
export const GET_PACKAGES_FAILURE = "GET_PACKAGES_FAILURE";

export const GET_PENDING_STATUS_VENUES = "GET_PENDING_STATUS_VENUES";
export const GET_PENDING_STATUS_VENUES_SUCCESS =
  "GET_PENDING_STATUS_VENUES_SUCCESS";
export const GET_PENDING_STATUS_VENUES_FAILURE =
  "GET_PENDING_STATUS_VENUES_FAILURE";

/*****************************  Map Constants  *************************************/

export const REVERSE_GEOCODING = "REVERSE_GEOCODING";
export const REVERSE_GEOCODING_SUCCESS = "REVERSE_GEOCODING_SUCCESS";
export const REVERSE_GEOCODING_FAILURE = "REVERSE_GEOCODING_FAILURE";

/*****************************  Dashboard Constants  *************************************/

export const GET_VENUES_BY_USER_ID = "GET_VENUES_BY_USER_ID";
export const GET_VENUES_BY_USER_ID_SUCCESS = "GET_VENUES_BY_USER_ID_SUCCESS";
export const GET_VENUES_BY_USER_ID_FAILURE = "GET_VENUES_BY_USER_ID_FAILURE";

export const CHANGE_OBJ_STATUS = "CHANGE_OBJ_STATUS";
export const CHANGE_OBJ_STATUS_SUCCESS = "CHANGE_OBJ_STATUS_SUCCESS";
export const CHANGE_OBJ_STATUS_FAILURE = "CHANGE_OBJ_STATUS_FAILURE";

export const SAVE_BOOKING_ITEM = "SAVE_BOOKING_ITEM";

export const GET_BOOKING_ITEM = "GET_BOOKING_ITEM";
export const GET_BOOKING_ITEM_SUCCESS = "GET_BOOKING_ITEM_SUCCESS";
export const GET_BOOKING_ITEM_FAILURE = "GET_BOOKING_ITEM_FAILURE";

export const GET_PENDING_BOOKING_STATUS = "GET_PENDING_BOOKING_STATUS";
export const GET_PENDING_BOOKING_STATUS_SUCCESS = "GET_PENDING_BOOKING_STATUS_SUCCESS";
export const GET_PENDING_BOOKING_STATUS_FAILURE = "GET_PENDING_BOOKING_STATUS_FAILURE";

export const GET_PENDING_BOOKING_APPROVAL = "GET_PENDING_BOOKING_APPROVAL";
export const GET_PENDING_BOOKING_APPROVAL_SUCCESS = "GET_PENDING_BOOKING_APPROVAL_SUCCESS";
export const GET_PENDING_BOOKING_APPROVAL_FAILURE = "GET_PENDING_BOOKING_APPROVAL_FAILURE";

export const GET_ORDER_CONFIRMATION_ITEM = "GET_ORDER_CONFIRMATION_ITEM";
export const GET_ORDER_CONFIRMATION_ITEM_SUCCESS =
  "GET_ORDER_CONFIRMATION_ITEM_SUCCESS";
export const GET_ORDER_CONFIRMATION_ITEM_FAILURE =
  "GET_ORDER_CONFIRMATION_ITEM_FAILURE";

export const GET_VENUE_FOR_BOOKED_DETAILS = "GET_VENUE_FOR_BOOKED_DETAILS";
export const GET_VENUE_FOR_BOOKED_DETAILS_SUCCESS =
  "GET_VENUE_FOR_BOOKED_DETAILS_SUCCESS";
export const GET_VENUE_FOR_BOOKED_DETAILS_FAILURE =
  "GET_VENUE_FOR_BOOKED_DETAILS_FAILURE";

export const CREATE_FEEDBACK = "CREATE_FEEDBACK";
export const CREATE_FEEDBACK_SUCCESS = "CREATE_FEEDBACK_SUCCESS";
export const CREATE_FEEDBACK_FAILURE = "CREATE_FEEDBACK_FAILURE";

export const GET_FEEDBACKS = "GET_FEEDBACKS";
export const GET_FEEDBACKS_SUCCESS = "GET_FEEDBACKS_SUCCESS";
export const GET_FEEDBACKS_FAILURE = "GET_FEEDBACKS_FAILURE";

/*****************************  Get User Constants  *************************************/

export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAILURE = "GET_USER_BY_ID_FAILURE";

/*****************************  Get Address Constants  *************************************/

export const GET_COUNTRY = "GET_COUNTRY";
export const GET_COUNTRY_SUCCESS = "GET_COUNTRY_SUCCESS";
export const GET_COUNTRY_FAILURE = "GET_COUNTRY_FAILURE";

export const GET_STATE = "GET_STATE";
export const GET_STATE_SUCCESS = "GET_STATE_SUCCESS";
export const GET_STATE_FAILURE = "GET_STATE_FAILURE";

export const GET_CITY = "GET_CITY";
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const GET_CITY_FAILURE = "GET_CITY_FAILURE";

/*****************************  Extra Constants  *************************************/

export const POST_SIGNUP = "POST_SIGNUP";
export const POST_SIGNUP_SUCCESS = "POST_SIGNUP_SUCCESS";
export const POST_SIGNUP_FAILURE = "POST_SIGNUP_FAILURE";

export const CONFIRM_SIGNUP = "CONFIRM_SIGNUP";
export const CONFIRM_SIGNUP_SUCCESS = "CONFIRM_SIGNUP_SUCCESS";
export const CONFIRM_SIGNUP_FAILURE = "CONFIRM_SIGNUP_FAILURE";

export const POST_CONFIRM = "POST_CONFIRM";
export const POST_CONFIRM_SUCCESS = "POST_CONFIRM_SUCCESS";
export const POST_CONFIRM_FAILURE = "POST_CONFIRM_FAILURE";

export const RESEND_SIGNUP = "RESEND_SIGNUP";
export const RESEND_SIGNUP_SUCCESS = "RESEND_SIGNUP_SUCCESS";
export const RESEND_SIGNUP_FAILURE = "RESEND_SIGNUP_FAILURE";
